# Generated by Django 5.1.6 on 2025-02-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_room_name_remove_room_type_room_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_occupancy',
            field=models.IntegerField(default=2),
        ),
    ]
