# Generated by Django 5.1.6 on 2025-02-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_room_max_occupancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='max_occupancy',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
