# Generated by Django 5.1.6 on 2025-02-28 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_room_max_occupancy_alter_room_room_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='max_occupancy',
        ),
    ]
